name: tsrct_dart_lib
description: library for common tsrct constructs
version: 1.0.2
repository: https://github.com/tsrct/tsrct-dart-lib

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  pointycastle: ^3.7.3
  http: ^1.1.0
  intl: ^0.18.1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
